openapi: 3.0.0
info:
  version: 2017-09-01
  x-release: v4
  title: 'AWS Elemental MediaStore #X Amz Target=MediaStore 20170901.CreateContainer #X Amz Target=MediaStore 20170901.CreateContainer #X Amz Target=MediaStore 20170901.GetMetricPolicy API'
  description: 'An AWS Elemental MediaStore container is a namespace that holds folders and objects. You use a container endpoint to create, read, and delete objects. '
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: mediastore
  x-aws-signingName: mediastore
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/mediastore-2017-09-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://mediastore.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The MediaStore multi-region endpoint
- url: https://mediastore.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The MediaStore multi-region endpoint
- url: http://mediastore.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The MediaStore endpoint for China (Beijing) and China (Ningxia)
- url: https://mediastore.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The MediaStore endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=MediaStore 20170901.GetMetricPolicy'
paths:
  /#X-Amz-Target=MediaStore_20170901.GetMetricPolicy:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetMetricPolicy
      description: 'Returns the metric policy for the specified container. '
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMetricPolicyOutput'
              examples:
                GetMetricPolicy200Example:
                  summary: Default GetMetricPolicy 200 response
                  x-microcks-default: true
                  value:
                    MetricPolicy: example-value
        '480':
          description: ContainerNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContainerNotFoundException'
              examples:
                GetMetricPolicy480Example:
                  summary: Default GetMetricPolicy 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: PolicyNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyNotFoundException'
              examples:
                GetMetricPolicy481Example:
                  summary: Default GetMetricPolicy 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ContainerInUseException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContainerInUseException'
              examples:
                GetMetricPolicy482Example:
                  summary: Default GetMetricPolicy 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              examples:
                GetMetricPolicy483Example:
                  summary: Default GetMetricPolicy 483 response
                  x-microcks-default: true
                  value: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetMetricPolicyInput'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - MediaStore_20170901.GetMetricPolicy
      summary: Amazon MediaStore Get Metric Policy
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=MediaStore 20170901.GetMetricPolicy'
components:
  parameters:
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  schemas:
    ContainerName:
      type: string
      pattern: '[\w-]+'
      minLength: 1
      maxLength: 255
    ContainerInUseException: {}
    InternalServerError: {}
    MetricPolicyRule:
      type: object
      required:
      - ObjectGroup
      - ObjectGroupName
      properties:
        ObjectGroup:
          allOf:
          - $ref: '#/components/schemas/ObjectGroup'
          - description: A path or file name that defines which objects to include in the group. Wildcards (*) are acceptable.
        ObjectGroupName:
          allOf:
          - $ref: '#/components/schemas/ObjectGroupName'
          - description: A name that allows you to refer to the object group.
      description: A setting that enables metrics at the object level. Each rule contains an object group and an object group name. If the policy includes the MetricPolicyRules parameter, you must include at least one rule. Each metric policy can include up to five rules by default. You can also <a href="https://console.aws.amazon.com/servicequotas/home?region=us-east-1#!/services/mediastore/quotas">request a quota increase</a> to allow up to 300 rules per policy.
    GetMetricPolicyOutput:
      type: object
      required:
      - MetricPolicy
      properties:
        MetricPolicy:
          allOf:
          - $ref: '#/components/schemas/MetricPolicy'
          - description: The metric policy that is associated with the specific container.
    ContainerLevelMetrics:
      type: string
      enum:
      - ENABLED
      - DISABLED
    MetricPolicy:
      type: object
      required:
      - ContainerLevelMetrics
      properties:
        ContainerLevelMetrics:
          allOf:
          - $ref: '#/components/schemas/ContainerLevelMetrics'
          - description: A setting to enable or disable metrics at the container level.
        MetricPolicyRules:
          allOf:
          - $ref: '#/components/schemas/MetricPolicyRules'
          - description: A parameter that holds an array of rules that enable metrics at the object level. This parameter is optional, but if you choose to include it, you must also include at least one rule. By default, you can include up to five rules. You can also <a href="https://console.aws.amazon.com/servicequotas/home?region=us-east-1#!/services/mediastore/quotas">request a quota increase</a> to allow up to 300 rules per policy.
      description: <p>The metric policy that is associated with the container. A metric policy allows AWS Elemental MediaStore to send metrics to Amazon CloudWatch. In the policy, you must indicate whether you want MediaStore to send container-level metrics. You can also include rules to define groups of objects that you want MediaStore to send object-level metrics for.</p> <p>To view examples of how to construct a metric policy for your use case, see <a href="https://docs.aws.amazon.com/mediastore/latest/ug/policies-metric-examples.html">Example Metric Policies</a>.</p>
    ObjectGroup:
      type: string
      pattern: /?(?:[A-Za-z0-9_=:\.\-\~\*]+/){0,10}(?:[A-Za-z0-9_=:\.\-\~\*]+)?/?
      minLength: 1
      maxLength: 900
    ContainerNotFoundException: {}
    ObjectGroupName:
      type: string
      pattern: '[a-zA-Z0-9_]+'
      minLength: 1
      maxLength: 30
    MetricPolicyRules:
      type: array
      items:
        $ref: '#/components/schemas/MetricPolicyRule'
      minItems: 1
      maxItems: 300
    PolicyNotFoundException: {}
    GetMetricPolicyInput:
      type: object
      required:
      - ContainerName
      title: GetMetricPolicyInput
      properties:
        ContainerName:
          allOf:
          - $ref: '#/components/schemas/ContainerName'
          - description: The name of the container that is associated with the metric policy.
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/mediastore/
x-hasEquivalentPaths: true
