openapi: 3.0.0
info:
  version: 2017-09-01
  x-release: v4
  title: 'AWS Elemental MediaStore #X Amz Target=MediaStore 20170901.CreateContainer #X Amz Target=MediaStore 20170901.CreateContainer #X Amz Target=MediaStore 20170901.GetCorsPolicy API'
  description: 'An AWS Elemental MediaStore container is a namespace that holds folders and objects. You use a container endpoint to create, read, and delete objects. '
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: mediastore
  x-aws-signingName: mediastore
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/mediastore-2017-09-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://mediastore.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The MediaStore multi-region endpoint
- url: https://mediastore.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The MediaStore multi-region endpoint
- url: http://mediastore.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The MediaStore endpoint for China (Beijing) and China (Ningxia)
- url: https://mediastore.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The MediaStore endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=MediaStore 20170901.GetCorsPolicy'
paths:
  /#X-Amz-Target=MediaStore_20170901.GetCorsPolicy:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetCorsPolicy
      description: <p>Returns the cross-origin resource sharing (CORS) configuration information that is set for the container.</p> <p>To use this operation, you must have permission to perform the <code>MediaStore:GetCorsPolicy</code> action. By default, the container owner has this permission and can grant it to others.</p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCorsPolicyOutput'
              examples:
                GetCorsPolicy200Example:
                  summary: Default GetCorsPolicy 200 response
                  x-microcks-default: true
                  value:
                    CorsPolicy: example-value
        '480':
          description: ContainerInUseException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContainerInUseException'
              examples:
                GetCorsPolicy480Example:
                  summary: Default GetCorsPolicy 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: ContainerNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContainerNotFoundException'
              examples:
                GetCorsPolicy481Example:
                  summary: Default GetCorsPolicy 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: CorsPolicyNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CorsPolicyNotFoundException'
              examples:
                GetCorsPolicy482Example:
                  summary: Default GetCorsPolicy 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              examples:
                GetCorsPolicy483Example:
                  summary: Default GetCorsPolicy 483 response
                  x-microcks-default: true
                  value: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetCorsPolicyInput'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - MediaStore_20170901.GetCorsPolicy
      summary: Amazon MediaStore Get Cors Policy
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=MediaStore 20170901.GetCorsPolicy'
components:
  schemas:
    MaxAgeSeconds:
      type: integer
      minimum: 0
      maximum: 2147483647
    ContainerName:
      type: string
      pattern: '[\w-]+'
      minLength: 1
      maxLength: 255
    ContainerInUseException: {}
    MethodName:
      type: string
      enum:
      - PUT
      - GET
      - DELETE
      - HEAD
    InternalServerError: {}
    GetCorsPolicyOutput:
      type: object
      required:
      - CorsPolicy
      properties:
        CorsPolicy:
          allOf:
          - $ref: '#/components/schemas/CorsPolicy'
          - description: The CORS policy assigned to the container.
    CorsPolicy:
      type: array
      description: 'The CORS policy of the container. '
      items:
        $ref: '#/components/schemas/CorsRule'
      minItems: 1
      maxItems: 100
    CorsRule:
      type: object
      required:
      - AllowedOrigins
      - AllowedHeaders
      properties:
        AllowedOrigins:
          allOf:
          - $ref: '#/components/schemas/AllowedOrigins'
          - description: <p>One or more response headers that you want users to be able to access from their applications (for example, from a JavaScript <code>XMLHttpRequest</code> object).</p> <p>Each CORS rule must have at least one <code>AllowedOrigins</code> element. The string value can include only one wildcard character (*), for example, http://*.example.com. Additionally, you can specify only one wildcard character to allow cross-origin access for all origins.</p>
        AllowedMethods:
          allOf:
          - $ref: '#/components/schemas/AllowedMethods'
          - description: <p>Identifies an HTTP method that the origin that is specified in the rule is allowed to execute.</p> <p>Each CORS rule must contain at least one <code>AllowedMethods</code> and one <code>AllowedOrigins</code> element.</p>
        AllowedHeaders:
          allOf:
          - $ref: '#/components/schemas/AllowedHeaders'
          - description: <p>Specifies which headers are allowed in a preflight <code>OPTIONS</code> request through the <code>Access-Control-Request-Headers</code> header. Each header name that is specified in <code>Access-Control-Request-Headers</code> must have a corresponding entry in the rule. Only the headers that were requested are sent back. </p> <p>This element can contain only one wildcard character (*).</p>
        MaxAgeSeconds:
          allOf:
          - $ref: '#/components/schemas/MaxAgeSeconds'
          - description: <p>The time in seconds that your browser caches the preflight response for the specified resource.</p> <p>A CORS rule can have only one <code>MaxAgeSeconds</code> element.</p>
        ExposeHeaders:
          allOf:
          - $ref: '#/components/schemas/ExposeHeaders'
          - description: <p>One or more headers in the response that you want users to be able to access from their applications (for example, from a JavaScript <code>XMLHttpRequest</code> object).</p> <p>This element is optional for each rule.</p>
      description: A rule for a CORS policy. You can add up to 100 rules to a CORS policy. If more than one rule applies, the service uses the first applicable rule listed.
    ExposeHeaders:
      type: array
      items:
        $ref: '#/components/schemas/Header'
      minItems: 0
      maxItems: 100
    GetCorsPolicyInput:
      type: object
      required:
      - ContainerName
      title: GetCorsPolicyInput
      properties:
        ContainerName:
          allOf:
          - $ref: '#/components/schemas/ContainerName'
          - description: The name of the container that the policy is assigned to.
    Header:
      type: string
      pattern: '[\u0009\u000A\u000D\u0020-\u00FF]+'
      minLength: 1
      maxLength: 8192
    ContainerNotFoundException: {}
    AllowedOrigins:
      type: array
      items:
        $ref: '#/components/schemas/Origin'
      minItems: 1
      maxItems: 100
    Origin:
      type: string
      pattern: '[\u0009\u000A\u000D\u0020-\u00FF]+'
      minLength: 1
      maxLength: 2048
    AllowedMethods:
      type: array
      items:
        $ref: '#/components/schemas/MethodName'
      minItems: 1
      maxItems: 4
    CorsPolicyNotFoundException: {}
    AllowedHeaders:
      type: array
      items:
        $ref: '#/components/schemas/Header'
      minItems: 0
      maxItems: 100
  parameters:
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/mediastore/
x-hasEquivalentPaths: true
